export const BASE_URL = "http://localhost:3000";
export const PISTON_API_URL = "https://emkc.org/api/v2/piston";

export const RUNTIMES = [
  {
    id: 1,
    language: "bash",
    version: "5.2.0",
    aliases: ["sh"],
  },
  {
    id: 2,
    language: "cobol",
    version: "3.1.2",
    aliases: ["cob"],
  },
  {
    id: 3,
    language: "coffeescript",
    version: "2.5.1",
    aliases: ["coffeescript", "coffee"],
  },
  {
    id: 4,
    language: "dart",
    version: "2.19.6",
    aliases: [],
  },
  {
    id: 5,
    language: "fsharp.net",
    version: "5.0.201",
    aliases: [
      "fsharp",
      "fs",
      "f#",
      "fs.net",
      "f#.net",
      "fsharp-dotnet",
      "fs-dotnet",
      "f#-dotnet",
      "dotnet-fsharp",
      "dotnet-fs",
      "dotnet-fs",
    ],
    runtime: "dotnet",
  },
  {
    id: 6,
    language: "csharp.net",
    version: "5.0.201",
    aliases: [
      "csharp",
      "c#",
      "cs",
      "c#.net",
      "cs.net",
      "c#-dotnet",
      "cs-dotnet",
      "csharp-dotnet",
      "dotnet-c#",
      "dotnet-cs",
      "dotnet-csharp",
    ],
    runtime: "dotnet",
  },
  {
    id: 7,
    language: "fsi",
    version: "5.0.201",
    aliases: [
      "fsx",
      "fsharp-interactive",
      "f#-interactive",
      "dotnet-fsi",
      "fsi-dotnet",
      "fsi.net",
    ],
    runtime: "dotnet",
  },

  {
    id: 8,
    language: "elixir",
    version: "1.11.3",
    aliases: ["elixir", "exs"],
  },
  {
    id: 9,
    language: "emacs",
    version: "27.1.0",
    aliases: ["emacs", "el", "elisp"],
  },
  {
    id: 10,
    language: "erlang",
    version: "23.0.0",
    aliases: ["erlang", "erl", "escript"],
  },
  {
    id: 11,
    language: "c",
    version: "10.2.0",
    aliases: ["gcc"],
    runtime: "gcc",
  },
  {
    id: 12,
    language: "c++",
    version: "10.2.0",
    aliases: ["cpp", "g++"],
    runtime: "gcc",
  },
  {
    id: 13,
    language: "fortran",
    version: "10.2.0",
    aliases: ["fortran", "f90"],
    runtime: "gcc",
  },
  {
    id: 14,
    language: "go",
    version: "1.16.2",
    aliases: ["go", "golang"],
  },
  {
    id: 15,
    language: "haskell",
    version: "9.0.1",
    aliases: ["haskell", "hs"],
  },
  {
    id: 16,
    language: "java",
    version: "15.0.2",
    aliases: [],
  },
  {
    id: 17,
    language: "julia",
    version: "1.8.5",
    aliases: ["jl"],
  },
  {
    id: 18,
    language: "kotlin",
    version: "1.8.20",
    aliases: ["kt"],
  },
  {
    id: 19,
    language: "lisp",
    version: "2.1.2",
    aliases: ["lisp", "cl", "sbcl", "commonlisp"],
  },
  {
    id: 20,
    language: "lua",
    version: "5.4.4",
    aliases: [],
  },
  {
    id: 21,
    language: "csharp",
    version: "6.12.0",
    aliases: ["mono", "mono-csharp", "mono-c#", "mono-cs", "c#", "cs"],
    runtime: "mono",
  },
  {
    id: 22,
    language: "javascript",
    version: "18.15.0",
    aliases: ["node-javascript", "node-js", "javascript", "js"],
    runtime: "node",
  },
  {
    id: 23,
    language: "ocaml",
    version: "4.12.0",
    aliases: ["ocaml", "ml"],
  },
  {
    id: 24,
    language: "octave",
    version: "8.1.0",
    aliases: ["matlab", "m"],
  },
  {
    id: 25,
    language: "perl",
    version: "5.36.0",
    aliases: ["pl"],
  },
  {
    id: 26,
    language: "php",
    version: "8.2.3",
    aliases: [],
  },
  {
    id: 27,
    language: "powershell",
    version: "7.1.4",
    aliases: ["ps", "pwsh", "ps1"],
    runtime: "pwsh",
  },

  {
    id: 28,
    language: "python",
    version: "3.10.0",
    aliases: ["py", "py3", "python3", "python3.10"],
  },

  {
    id: 29,
    language: "rscript",
    version: "4.1.1",
    aliases: ["r"],
  },

  {
    id: 30,
    language: "ruby",
    version: "3.0.1",
    aliases: ["ruby3", "rb"],
  },
  {
    id: 31,
    language: "rust",
    version: "1.68.2",
    aliases: ["rs"],
  },

  {
    id: 32,
    language: "scala",
    version: "3.2.2",
    aliases: ["sc"],
  },
  {
    id: 33,
    language: "swift",
    version: "5.3.3",
    aliases: ["swift"],
  },
  {
    id: 34,
    language: "typescript",
    version: "5.0.3",
    aliases: ["ts", "node-ts", "tsc", "typescript5", "ts5"],
  },
  {
    id: 35,
    language: "zig",
    version: "0.10.1",
    aliases: [],
  },
];
